#ngtms.product.mode=false
#################################
########        HCCE     ########
#################################
#### hcce.node.name, hcce.primary.group.name, hcce.backup.group.name can use %HostName%, %Random%, %UUID% placeholder variables.
hcce.node.name=D3RT5XM3
hcce.primary.group.name=hc_primary_group
hcce.backup.group.name=hc_backup_group
hcce.in.primary.group=true
### default 4320.
hcce.rmi.registry.port=4320
### default 20 sec. Unit: sec.
hcce.fme.management.first.delay=20
### default 5 sec. Unit: sec.
hcce.fme.management.interval=5

hcce.clientNode.group=hc_client_group
hcce.clientNode.heartbeat.fail.seconds = 90
hcce.clientNode.heartbeat.checker.cron = 20/30 * * * * ?

#################################
########    Hazelcast    ########
#################################
### Please use GenHzConfigMd5Hash to generate the md5 hash value of hazelcast.xml file
hz.md5.value=4ff2baff1448069f3d3e9042f116c0f0
### hazelcast instance name is equal to hcce node name
hz.group.password = please_change_password
hz.members = D3RT5XM3:${hz.network.port}
hz.network.port = 5901
hz.multicast.enabled=true
hz.multicast.group=224.2.2.27
hz.multicast.port=54321
hz.binding.interface=10.121.41.38
hz.icmp.enabled=true
hz.icmp.ttl=16
hz.merge.first.run.delay.seconds=60
hz.merge.next.run.delay.seconds=60
### \u5728 Product mode \u5EFA\u8B70\u5C07hz.performance.ioThreadCount \u8A2D\u70BA 12 , \u9019\u4EE3\u8868  1 \u500B accept-IO-thread, 12 \u500B read-IOthreads, and 12\u500B  write-IO-threads
hz.performance.ioThreadCount=3
### \u5728 Product mode \u5EFA\u8B70\u5C07 hz.performance.eventThreadCount \u8A2D\u70BA 32
hz.performance.eventThreadCount=5
hz.imap.defaultBackupCount=2
hz.imap.defaultAsyncBackupCount=0
hz.imap.readBackupData=true
hz.iqueue.defaultBackupCount=1
hz.iqueue.defaultAsyncBackupCount=0

hz.management.center.enabled = false
hz.management.center.url = http://localhost:8080/mancenter

### client parameters, for duplicated node name testing
hz.client.connection.timeout=1000
hz.client.connection.attempt.limit=1

#############################################
######## Online Database Data Source ########
#############################################
### MySQL
olds.driverClassName=com.mysql.cj.jdbc.MysqlDataSource
olds.url=jdbc:mysql://127.0.0.1:3306/ao?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
olds.username=ao
olds.password=aoAdmin
olds.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

olds.hibernate.format_sql=false
olds.hibernate.show_sql=true
### allowable value: none, validate, update, create, create-drop
olds.hibernate.hbm2ddl.auto=create-drop
olds.packages.to.scan=com.hwacom.ngtms.**.model
olds.enable.password.encryption=false

### Hikari connection pool
olds.connectionTestQuery=select 1 from dual
olds.maximumPoolSize=120
olds.maxLifetime=1800000
olds.connectionTimeout=10000

#################################
########      i18n       ########
#################################
i18n.baseDirectory=classpath*:messages
i18n.cacheSeconds=-1
#i18n.baseDirectory=/WEB-INF/messages
#i18n.cacheSeconds=60

#################################
######## SSH Host Alias  ########
#################################
ssh.oldb.host=hc_oldb
ssh.oldb.username=mysql
ssh.oldb.privatekey=sshPrivateKey/oldb_rsa
ssh.oldb.privatekey.password=12345

#################################
######## Message Service ########
#################################
mail.host=smtp.gmail.com
mail.port=587
mail.username=itsgood.mail2010@gmail.com
mail.password=!@#$RFVCXZ
#mail.transport.protocol=smtp
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.debug=false

##################################
######## SysPerfLog alarm ########
##################################
sysPerfLog.mail.enabled=false
# \u6BCF\u500B job \u6700\u5927\u4FDD\u7559 log \u8A0A\u606F\u7B46\u6578
sysPerfLog.mail.maxLogBufferSize=20
sysPerfLog.mail.alarm.properties=conf/sysPerfLogAlarm.properties
# \u6700\u5C0F\u8B66\u5831\u9031\u671F\uFF0C\u55AE\u4F4D \u79D2
sysPerfLog.mail.alarm.period=3600
sysPerfLog.mail.from=itsgood.mail2010@gmail.com
# \u8ACB\u793A\u4F7F\u7528 "," \u9694\u958B\u591A\u500B\u63A5\u6536\u8005
sysPerfLog.mail.to=
sysPerfLog.mail.subject=aoCluster SysPerfLog notify

### SMS
sms.enabled=false
sms.account=10371
sms.password=10371

## HTTP Proxy
http.proxy.ip=
http.proxy.port=3128

dir.output=D:/xml
xml.pdOperation=1min_pd_operation_data.xml
xml.pdConfig=1day_pd_config_data.xml

####################################
##### Security AD Configuration #####
####################################
security.ad.domain=tcloud.freeway.local
security.ad.url=ldap://10.125.3.27:389/
security.ad.base=DC=tcloud,DC=freeway,DC=local
security.ad.manager.dn=tcloudldap
security.ad.manager.secret=1qaz@WSX3edc$RFV
security.ad.roleLikes = eac
#security.ad.searchBase= OU=交通部高速公路局
security.ad.searchBase=OU=\u4ea4\u901a\u90e8\u9ad8\u901f\u516c\u8def\u5c40

report.usingRptServiceRemotePolicy=false
report.exportDirection=/shared/rpt/
report.exportUrl=http://10.121.41.38/rpt/